server:
  port: 8080
wx:
  token: jensvnunionapi
  appId: wx1a68402642f8c48a
  appSecret: 27ec7b8ffb4261657ca4d4b869c6c0a0
  encodingAESKey: 0Asfg1yeQoAkkC4GpKQYnQZQTZtIQF92Zfhzygdelxr
  accessTokenUrl: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid={APPID}&secret={APPSECRET}
  createMenuUrl: https://api.weixin.qq.com/cgi-bin/menu/create?access_token={ACCESS_TOKEN}

taobao:
  server: http://gw.api.taobao.com/router/rest
  mama:
    key: 28189674
    secret: 5d36ee67d5220f1ab991afcfdc86ee38
    adzoneId: 109714600357
jd:
  server: https://router.jd.com/api
  union:
    key: #京东联盟 key
    secret: #京东联盟 secret
    siteId: #京东联盟 siteId

url:
  jd: https://router.jd.com/api #京东联盟 正式环境url